# src/classification/train_cascade.py
"""
Confidence-based CASCADE classifier for IT-support-ticket routing.
================================================================================

WHAT THIS FILE DOES
-------------------
Implements and evaluates a two-tier confidence-based cascade classifier:

    Tier 1 (cheap):     TF-IDF + LogisticRegression. Runs first on EVERY ticket.
    Decision rule:      if Tier 1's predicted-class probability (predict_proba
                        max) >= CASCADE_CONFIDENCE_THRESHOLD -> ACCEPT Tier 1's
                        prediction. Done. No Tier 2 call needed.
    Tier 2 (expensive): sentence-transformers "all-MiniLM-L6-v2" embeddings +
                        LogisticRegression. Only invoked when Tier 1 is NOT
                        confident enough; its prediction then overrides Tier 1's.

WHY THIS DESIGN (the "don't guess when uncertain, escalate instead" principle)
------------------------------------------------------------------------------
This mirrors EXACTLY the same philosophy already used one level up in this
project's RAG layer. In src/rag/suggest_resolution.py there is a
SIMILARITY_THRESHOLD = 0.35 guard: when retrieval confidence is too low, the
code REFUSES to guess with the LLM and instead escalates the ticket to a human.

This cascade applies the identical philosophy one level DOWN - at
model-selection time instead of ticket-resolution time. Instead of "retrieval
too weak -> escalate to a human", here it is "cheap model too unsure -> escalate
to the expensive model". Same idea, different layer: never spend an expensive
call (or make a confident-sounding guess) when the cheap/confident path is
untrustworthy.

This is a FrugalGPT-style cascade: route the easy cases through the cheap model
and only pay for the expensive model on the hard cases. Even if end accuracy
does not jump dramatically, the EFFICIENCY win (fraction of traffic served by
the cheap tier) is a first-class result and is reported honestly either way.

CALIBRATION FIRST
-----------------
We do NOT hardcode an arbitrary confidence threshold. We first measure whether
Tier 1's predict_proba is trustworthy (reliability / calibration table), then
DERIVE the threshold from the point where Tier 1's actual accuracy drops below a
stated target band (~90-95%). Classifier probabilities (like LLM confidences)
are frequently over-confident, so we verify empirically rather than taking the
raw score at face value.

IMPORTANT (why we calibrate on a SEPARATE paraphrased set)
-----------------------------------------------------------
The held-out 800-row test split is drawn from the SAME synthetic templates as
training, so Tier-1 (TF-IDF) shows ~100% accuracy in every confidence bucket
there. That in-distribution perfection makes the derivation rule pick an
unreliably-low threshold that fails on real out-of-distribution phrasing. To
fix this we ALSO calibrate on a separate, denser calibration set of plain,
non-template, paraphrased tickets loaded from
data/calibration_tickets_paraphrased.json (175 tickets, 25 per category,
generated by src/classification/generate_calibration_set.py) - and use THAT
derived threshold for the cascade. The held-out-split calibration is still
printed first for comparison, but the calibration-set threshold is the one
actually applied.

NOTE: the loaded calibration set is kept COMPLETELY INDEPENDENT of
NOVEL_TICKETS. NOVEL_TICKETS is used ONLY for final benchmark evaluation and
never for threshold derivation, so the benchmark stays uncontaminated.

TRADEOFF ANALYSIS (accuracy/efficiency bars)
---------------------------------------------
The single-threshold derivation above uses ONE stated accuracy bar
(TIER1_ACCEPT_ACCURACY_TARGET = 0.90). At that 90% bar the calibration set's
confidence distribution may not support any cheap-tier usage at all (threshold
collapses to 1.00, 100% Tier-2). To characterize the tradeoff properly we ALSO
sweep a small set of LOWER accuracy bars (ACCURACY_TARGETS_TO_TEST) and report,
for each, the derived threshold and the resulting Tier-1 usage / accuracy on
both the held-out split and the 14 novel tickets. This turns a single negative
result into a proper accuracy/efficiency tradeoff table for the results section.
Lowering the bar is a legitimate, statable design choice: we accept up to X%
more errors in exchange for Y% fewer expensive-tier calls.
"""

from __future__ import annotations

import os
import sys
import json
import random

# --------------------------------------------------------------------------- #
# Dependency import guards (same pattern as the rest of this project)          #
# --------------------------------------------------------------------------- #
try:
    import numpy as np
except ImportError:
    print("[ERROR] Missing required package: numpy")
    print("        Install it with:  pip install numpy")
    sys.exit(1)

try:
    import pandas as pd
except ImportError:
    print("[ERROR] Missing required package: pandas")
    print("        Install it with:  pip install pandas")
    sys.exit(1)

try:
    from sklearn.model_selection import train_test_split
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import (
        accuracy_score,
        f1_score,
        classification_report,
        confusion_matrix,
    )
except ImportError:
    print("[ERROR] Missing required package: scikit-learn")
    print("        Install it with:  pip install scikit-learn")
    sys.exit(1)

# sentence-transformers is imported lazily inside train_tier2 / embedding code
# so that the calibration / Tier-1-only paths can still run if the heavy model
# is unavailable, and so the network/download error handling is localized.


# --------------------------------------------------------------------------- #
# Reproducibility (project convention)                                         #
# --------------------------------------------------------------------------- #
random.seed(42)
np.random.seed(42)

RANDOM_STATE = 42
TEST_SIZE = 0.2

# --------------------------------------------------------------------------- #
# Cascade threshold (DERIVED from calibration below - see run_calibration_     #
# analysis_on_calibration_set(). This is the default/fallback; __main__        #
# recomputes and reports the derived value explicitly.)                        #
# --------------------------------------------------------------------------- #
CASCADE_CONFIDENCE_THRESHOLD = 0.80  # default; overridden by derived value

# Target accuracy band Tier 1 must sustain to be "trusted" without escalation.
TIER1_ACCEPT_ACCURACY_TARGET = 0.90  # accept-tier accuracy we want to hold at

# Target accuracy bars swept by the tradeoff analysis (run_tradeoff_analysis).
# The FIRST/primary bar (0.90) is identical to TIER1_ACCEPT_ACCURACY_TARGET and
# reproduces the single-threshold result; the lower bars characterize the
# accuracy/efficiency tradeoff of relaxing the accept-tier accuracy requirement.
ACCURACY_TARGETS_TO_TEST = [0.90, 0.80, 0.70]

EMBED_MODEL_NAME = "all-MiniLM-L6-v2"

REQUIRED_COLUMNS = ["id", "title", "description", "category", "resolution", "priority"]
MIN_CATEGORIES = 7


# --------------------------------------------------------------------------- #
# THE generalization benchmark - 14 hand-written novel tickets.               #
# COPIED VERBATIM. Do not alter wording or labels.                            #
# --------------------------------------------------------------------------- #
NOVEL_TICKETS = [
    {"text": "I got a new laptop and now the system keeps saying my username "
             "or password is wrong even though I'm sure it's right. Can someone "
             "reset me so I can get back in?",
     "expected": "Access Management"},
    {"text": "My manager said I should be able to see the finance shared folder "
             "but it just says I'm not allowed. Can you give me permission to open it?",
     "expected": "Access Management"},
    {"text": "The wifi in the third floor meeting room keeps dropping every few "
             "minutes so we can't run our video calls. Everyone else in the "
             "building seems fine.",
     "expected": "Network"},
    {"text": "Pages take forever to load today and sometimes just time out. My "
             "colleague next to me has the same slowness on her machine too.",
     "expected": "Network"},
    {"text": "I keep getting a message that there's no room left to save my files "
             "and I can't download the report I need. It says the drive is full.",
     "expected": "Storage"},
    {"text": "I tried to save my presentation but it won't let me because it says "
             "I've run out of space in my folder. How do I free some up?",
     "expected": "Storage"},
    {"text": "When I try to pull up last month's customer records the whole thing "
             "just spins and then shows an error about not being able to reach the "
             "records system.",
     "expected": "Database"},
    {"text": "The report tool says it can't find the numbers it needs and mentions "
             "something about a broken connection to where the data is kept.",
     "expected": "Database"},
    {"text": "I got a weird email pretending to be from HR asking me to type in my "
             "password on a link, and I think I might have clicked it by mistake. "
             "What should I do?",
     "expected": "Security"},
    {"text": "My antivirus popped up a warning that something suspicious was blocked "
             "and now I'm worried my computer has a virus on it.",
     "expected": "Security"},
    {"text": "Every time I open the expense program it freezes on the loading screen "
             "and then closes itself. I've tried restarting but it keeps crashing.",
     "expected": "Application"},
    {"text": "The invoicing software gives me an error and shuts down whenever I "
             "click the print button. Nothing prints at all.",
     "expected": "Application"},
    {"text": "None of the company websites are working for anyone in the office this "
             "morning - it looks like one of the main servers might be down.",
     "expected": "Infrastructure"},
    {"text": "The whole team can't reach any of our internal tools and someone said "
             "a machine in the server room overheated and shut off overnight.",
     "expected": "Infrastructure"},
]

# Known baseline scores on the 14 novel tickets (from existing project scripts).
BASELINE_TFIDF_NOVEL = (7, 14)    # 50.0%
BASELINE_MINILM_NOVEL = (10, 14)  # 71.4%


# --------------------------------------------------------------------------- #
# Path resolution (project convention: root is TWO dirs up from this file).    #
# Works on Windows because we use os.path.* everywhere, no hardcoded slashes.  #
# --------------------------------------------------------------------------- #
def get_project_root() -> str:
    """Project root = two directories up from this script's own location."""
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(os.path.dirname(here))


PROJECT_ROOT = get_project_root()
CSV_PATH = os.path.join(PROJECT_ROOT, "data", "synthetic_tickets.csv")
EMBED_CACHE_PATH = os.path.join(PROJECT_ROOT, "data", "ticket_embeddings.npy")
CALIBRATION_JSON_PATH = os.path.join(PROJECT_ROOT, "data",
                                     "calibration_tickets_paraphrased.json")


# --------------------------------------------------------------------------- #
# Calibration set loading (replaces the old 35-ticket CALIBRATION_TICKETS      #
# list). The dense, paraphrased set is generated by a separate script:         #
#   src/classification/generate_calibration_set.py                             #
# and saved to data/calibration_tickets_paraphrased.json (175 tickets, 25 per  #
# category x 7). It exists SOLELY to derive CASCADE_CONFIDENCE_THRESHOLD on     #
# realistic, out-of-distribution phrasing (plain, paraphrased, non-template).   #
#                                                                              #
# It is INTENTIONALLY DISJOINT from NOVEL_TICKETS - different scenarios and    #
# wording - so that calibrating on it does NOT leak into or contaminate the    #
# 14-ticket final benchmark. NOVEL_TICKETS stays reserved for evaluation only; #
# this set is used only for threshold derivation. Records use the same dict    #
# shape ("text"/"expected") as NOVEL_TICKETS, so it is a drop-in replacement    #
# wherever the old CALIBRATION_TICKETS list was used.                          #
# --------------------------------------------------------------------------- #
def load_calibration_set(path: str = CALIBRATION_JSON_PATH):
    """Load and validate the paraphrased calibration set from JSON.

    - Requires the file to exist; if it does not, prints a clear message
      explaining it must be generated first, then exits.
    - Loads the JSON list and validates: it is a non-empty list, every record
      has "text" and "expected" keys. (The training-category validation is
      done separately in validate_calibration_labels-style code in main via
      the returned records; see validate_loaded_calibration_labels.)
    - Prints a short load summary: total loaded, per-category counts, and (FYI
      only) how many records are flagged, if a "flagged" key is present.
    - Returns a list of dicts with at least "text" and "expected" (same shape
      as NOVEL_TICKETS).
    """
    if not os.path.exists(path):
        print(f"[ERROR] Calibration set not found at:\n        {path}")
        print("        This file is the ONLY calibration source and must be "
              "generated first.")
        print("        Generate it by running:")
        print("            python src/classification/generate_calibration_set.py")
        sys.exit(1)

    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] Failed to read/parse calibration JSON at {path}: {exc}")
        sys.exit(1)

    # Must be a non-empty list.
    if not isinstance(data, list) or len(data) == 0:
        print(f"[ERROR] Calibration JSON at {path} must be a non-empty list of "
              f"records, got: {type(data).__name__} "
              f"(len={len(data) if hasattr(data, '__len__') else 'n/a'}).")
        print("        Regenerate it with:")
        print("            python src/classification/generate_calibration_set.py")
        sys.exit(1)

    # Every record must have "text" and "expected" keys. Do NOT silently drop
    # bad records - report all offenders clearly and exit.
    bad_records = []
    for i, rec in enumerate(data):
        if not isinstance(rec, dict):
            bad_records.append((i, f"record is {type(rec).__name__}, not an object"))
            continue
        missing_keys = [k for k in ("text", "expected") if k not in rec]
        if missing_keys:
            bad_records.append((i, f"missing key(s): {missing_keys}"))
            continue
        if not isinstance(rec["text"], str) or not rec["text"].strip():
            bad_records.append((i, "'text' is empty or not a string"))
            continue
        if not isinstance(rec["expected"], str) or not rec["expected"].strip():
            bad_records.append((i, "'expected' is empty or not a string"))

    if bad_records:
        print(f"[ERROR] Calibration JSON at {path} contains {len(bad_records)} "
              f"malformed record(s) (every record needs non-empty 'text' and "
              f"'expected' keys):")
        for i, why in bad_records:
            print(f"        record #{i}: {why}")
        print("        Regenerate it with:")
        print("            python src/classification/generate_calibration_set.py")
        sys.exit(1)

    # ---- Load summary --------------------------------------------------- #
    per_cat = {}
    for rec in data:
        per_cat[rec["expected"]] = per_cat.get(rec["expected"], 0) + 1
    n_flagged = sum(1 for rec in data if rec.get("flagged"))

    if n_flagged > 0:
        print(f"[calibration] Loaded {len(data)} tickets ({n_flagged} flagged for "
              f"label disagreement, used anyway - ground truth labels are "
              f"unaffected)")
    else:
        print(f"[calibration] Loaded {len(data)} tickets")
    print("[calibration] Per-category counts: " + "  ".join(
        f"{cat}={per_cat[cat]}" for cat in sorted(per_cat)
    ))

    # Return records preserving at least "text"/"expected" (drop-in shape). We
    # keep the full record so an optional "flagged" flag survives if present.
    return list(data)


# --------------------------------------------------------------------------- #
# Data loading + validation (same gates as the rest of this project)           #
# --------------------------------------------------------------------------- #
def load_and_validate_csv(csv_path: str = CSV_PATH) -> pd.DataFrame:
    """Load the ticket CSV and run the project's standard validation gates."""
    if not os.path.exists(csv_path):
        print(f"[ERROR] Could not find the dataset CSV at:\n        {csv_path}")
        print("        Expected data/synthetic_tickets.csv relative to project root.")
        print("        Run this script from the project root, or generate the dataset first.")
        sys.exit(1)

    try:
        df = pd.read_csv(csv_path)
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] Failed to read CSV at {csv_path}: {exc}")
        sys.exit(1)

    # Required columns present.
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        print(f"[ERROR] CSV is missing required columns: {missing}")
        print(f"        Found columns: {list(df.columns)}")
        sys.exit(1)

    # No NaNs in the fields we actually use.
    for col in ["title", "description", "category"]:
        n_nan = df[col].isna().sum()
        if n_nan > 0:
            print(f"[ERROR] Column '{col}' contains {n_nan} NaN value(s). "
                  f"Clean the dataset before training.")
            sys.exit(1)

    # At least MIN_CATEGORIES distinct categories.
    n_cats = df["category"].nunique()
    if n_cats < MIN_CATEGORIES:
        print(f"[ERROR] Expected at least {MIN_CATEGORIES} categories, "
              f"found only {n_cats}: {sorted(df['category'].unique())}")
        sys.exit(1)

    # Stratification sanity check: every class must have >= 2 rows so an 80/20
    # stratified split can place at least one row in each split.
    class_counts = df["category"].value_counts()
    too_small = class_counts[class_counts < 2]
    if len(too_small) > 0:
        print("[ERROR] These categories have fewer than 2 rows and cannot be "
              "stratified into a train/test split:")
        print(too_small.to_string())
        sys.exit(1)

    print(f"[data] Loaded {len(df)} tickets, {n_cats} categories from "
          f"{os.path.relpath(csv_path, PROJECT_ROOT)}")
    print(f"[data] Category balance:\n{class_counts.sort_index().to_string()}")
    return df


def build_text_series(df: pd.DataFrame) -> pd.Series:
    """Project-wide input text convention: title + ' ' + description."""
    return (df["title"].astype(str) + " " + df["description"].astype(str))


def standard_split(X, y):
    """The one split used everywhere in this project: 80/20, seed 42, stratified.

    Reusing this exact call guarantees the cascade is evaluated on the SAME
    800-row held-out test set that train_embeddings.py used.
    """
    return train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )


# --------------------------------------------------------------------------- #
# Tier 1: TF-IDF + LogisticRegression                                          #
# --------------------------------------------------------------------------- #
def train_tier1(X_train_text, y_train):
    """Fit the cheap Tier-1 model on the given training text.

    Returns (vectorizer, clf). Matches the project's Tier-A candidate config.
    """
    vectorizer = TfidfVectorizer(
        max_features=5000,
        ngram_range=(1, 2),
        stop_words="english",
    )
    X_train_tfidf = vectorizer.fit_transform(X_train_text)
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_train_tfidf, y_train)
    return vectorizer, clf


def get_tier1_confidence(vectorizer, clf, texts):
    """Return (predictions, confidences) for Tier 1 over an iterable of texts.

    confidence = max predict_proba over classes for each row.
    """
    X = vectorizer.transform(texts)
    proba = clf.predict_proba(X)
    preds = clf.classes_[np.argmax(proba, axis=1)]
    conf = np.max(proba, axis=1)
    return preds, conf


# --------------------------------------------------------------------------- #
# Tier 2: MiniLM embeddings + LogisticRegression                               #
# --------------------------------------------------------------------------- #
def _load_embedder():
    """Load the sentence-transformers model with the project's error handling.

    Only the FIRST ever call may hit the network to download the model; after
    that it is served from the local HuggingFace cache (no network call). We
    catch connection/timeout/proxy style failures explicitly with a clear
    message, matching the pattern used elsewhere in this project.
    """
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError:
        print("[ERROR] Missing required package: sentence-transformers")
        print("        Install it with:  pip install sentence-transformers")
        sys.exit(1)

    try:
        model = SentenceTransformer(EMBED_MODEL_NAME)
    except Exception as exc:  # noqa: BLE001
        msg = str(exc).lower()
        network_markers = (
            "connection", "timeout", "timed out", "proxy", "network",
            "max retries", "temporarily unavailable", "resolve", "ssl",
            "failed to establish", "unreachable", "getaddrinfo",
        )
        if any(marker in msg for marker in network_markers):
            print(f"[ERROR] Could not download the '{EMBED_MODEL_NAME}' model "
                  f"(network/download issue).")
            print(f"        Underlying error: {exc}")
            print("        If you are behind a proxy, set HTTP_PROXY/HTTPS_PROXY, "
                  "or pre-download the model once while online so it is cached "
                  "locally for offline runs.")
        else:
            print(f"[ERROR] Failed to load the '{EMBED_MODEL_NAME}' model: {exc}")
        sys.exit(1)
    return model


def compute_or_load_embeddings(texts, expected_rows, use_cache=True):
    """Return embeddings for `texts`, reusing data/ticket_embeddings.npy if valid.

    Cache policy (identical to train_embeddings.py):
      - cache HIT  : file exists AND its row count matches expected_rows -> load.
      - cache MISS : file absent OR row count mismatch -> recompute + overwrite.

    Only the FULL-dataset embeddings are cached (that is what the cache stores).
    For arbitrary subsets (e.g. the train split, or novel tickets) we compute
    on the fly and do not touch the cache. `use_cache` controls whether we even
    consider the cache for this call.
    """
    if use_cache and os.path.exists(EMBED_CACHE_PATH):
        try:
            cached = np.load(EMBED_CACHE_PATH)
        except Exception as exc:  # noqa: BLE001
            print(f"[cache MISS] Failed to read {EMBED_CACHE_PATH} ({exc}); "
                  f"recomputing embeddings.")
            cached = None
        if cached is not None:
            if cached.shape[0] == expected_rows:
                print(f"[cache HIT] Reusing embeddings from "
                      f"{os.path.relpath(EMBED_CACHE_PATH, PROJECT_ROOT)} "
                      f"({cached.shape[0]} rows, dim={cached.shape[1]}). "
                      f"Skipping ~100s re-embed.")
                return cached
            else:
                print(f"[cache MISS] Cache has {cached.shape[0]} rows but current "
                      f"data has {expected_rows} rows; recomputing + overwriting.")

    if use_cache:
        print(f"[cache MISS] No valid embeddings cache; embedding {expected_rows} "
              f"rows now (this is the slow step, ~100s for 4000 rows)...")
    model = _load_embedder()
    emb = model.encode(list(texts), show_progress_bar=True,
                       convert_to_numpy=True)
    emb = np.asarray(emb, dtype=np.float32)

    if use_cache and emb.shape[0] == expected_rows:
        try:
            np.save(EMBED_CACHE_PATH, emb)
            print(f"[cache WRITE] Saved embeddings to "
                  f"{os.path.relpath(EMBED_CACHE_PATH, PROJECT_ROOT)}")
        except Exception as exc:  # noqa: BLE001
            print(f"[warn] Could not write embeddings cache: {exc}")
    return emb


def train_tier2_from_embeddings(train_emb, y_train):
    """Fit the expensive Tier-2 classifier on precomputed training embeddings."""
    clf = LogisticRegression(max_iter=1000)
    clf.fit(train_emb, y_train)
    return clf


# --------------------------------------------------------------------------- #
# Reusable threshold derivation                                                 #
# --------------------------------------------------------------------------- #
def derive_threshold_for_target(tier1_conf, correct, target_accuracy):
    """Derive a cascade confidence threshold for an EXPLICIT target accuracy.

    This is the reusable core of the threshold-derivation logic that was
    previously inlined (and hardcoded to TIER1_ACCEPT_ACCURACY_TARGET) inside
    run_calibration_analysis / run_calibration_analysis_on_calibration_set.

    Rule (unchanged): bucket the given Tier-1 confidences into fixed bins, then
    scan the populated bins from high confidence downward and keep including a
    bin while the CUMULATIVE accuracy of everything at-or-above its lower edge
    holds at/above `target_accuracy`. The chosen threshold is that bin's lower
    edge. If no band sustains the target, escalate (almost) everything.

    Parameters
    ----------
    tier1_conf : array-like of float
        Tier-1 max predict_proba confidence per ticket.
    correct : array-like of {0,1}
        1 where Tier-1's prediction matched ground truth, else 0. (Callers pass
        (tier1_preds == y_true).astype(int).)
    target_accuracy : float
        The accept-tier accuracy the derived threshold must sustain.

    Returns
    -------
    (derived_threshold, chosen_edge) : (float, float | None)
        `derived_threshold` is the value applied as CASCADE_CONFIDENCE_THRESHOLD
        (1.0001 fallback -> escalate everything if nothing qualifies).
        `chosen_edge` is the lower edge that was selected, or None if no band
        sustained the target. Matches the previous inline result shape.
    """
    tier1_conf = np.asarray(tier1_conf)
    correct = np.asarray(correct)

    edges = [0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0001]
    labels = ["<50%", "50-60%", "60-70%", "70-80%", "80-90%", "90-100%"]

    # Build per-bin stats (lo, hi, label, count, acc) exactly as before.
    bin_stats = []
    for i in range(len(labels)):
        lo, hi = edges[i], edges[i + 1]
        mask = (tier1_conf >= lo) & (tier1_conf < hi)
        cnt = int(mask.sum())
        if cnt == 0:
            bin_stats.append((lo, min(hi, 1.0), labels[i], 0, None))
            continue
        acc = float(correct[mask].mean())
        bin_stats.append((lo, min(hi, 1.0), labels[i], cnt, acc))

    derived = 1.0001  # fallback: escalate everything if nothing qualifies
    ordered = sorted([b for b in bin_stats if b[3] > 0], key=lambda b: -b[0])
    chosen_edge = None
    for lo, hi, lab, cnt, acc in ordered:
        mask = tier1_conf >= lo
        cum_acc = float(correct[mask].mean()) if mask.sum() > 0 else 0.0
        if cum_acc >= target_accuracy:
            chosen_edge = lo  # keep lowering while target still met
            
    if chosen_edge is not None:
        derived = chosen_edge

    return float(derived), chosen_edge


# --------------------------------------------------------------------------- #
# Calibration analysis                                                          #
# --------------------------------------------------------------------------- #
def run_calibration_analysis(y_true, tier1_preds, tier1_conf):
    """Bucket Tier-1 predictions by confidence and report ACTUAL accuracy.

    Prints a reliability/calibration table and DERIVES a cascade threshold as
    the lowest confidence bin whose actual accuracy still holds at/above the
    stated target band. Returns the derived threshold (float).

    NOTE ON CALIBRATION: classifier predict_proba values - like LLM confidence
    scores - are frequently OVER-confident (they claim 90% but are right less
    often). We therefore never trust the raw score at face value; we measure
    empirically and set the escalation threshold from observed accuracy.
    """
    y_true = np.asarray(y_true)
    tier1_preds = np.asarray(tier1_preds)
    tier1_conf = np.asarray(tier1_conf)
    correct = (tier1_preds == y_true).astype(int)

    # Bins from 0.0 to 1.0 in 0.10 steps; we report populated bins from 0.5 up
    # (below 0.5 is rare for a 7-class max-proba but still bucketed).
    edges = [0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0001]
    labels = ["<50%", "50-60%", "60-70%", "70-80%", "80-90%", "90-100%"]

    print("\n" + "=" * 66)
    print("TIER-1 CONFIDENCE CALIBRATION (held-out test split)")
    print("=" * 66)
    print(f"{'confidence bucket':<18}{'count':>8}{'actual acc':>14}"
          f"{'over/under?':>18}")
    print("-" * 66)

    bin_stats = []  # (lo, hi, label, count, acc)
    for i in range(len(labels)):
        lo, hi = edges[i], edges[i + 1]
        mask = (tier1_conf >= lo) & (tier1_conf < hi)
        cnt = int(mask.sum())
        if cnt == 0:
            print(f"{labels[i]:<18}{cnt:>8}{'-':>14}{'':>18}")
            bin_stats.append((lo, min(hi, 1.0), labels[i], 0, None))
            continue
        acc = float(correct[mask].mean())
        # Compare actual accuracy to the MIDPOINT of the bucket's confidence
        # range to flag systematic over/under-confidence.
        mid = (lo + min(hi, 1.0)) / 2.0
        if acc < mid - 0.05:
            tag = "OVERCONFIDENT"
        elif acc > mid + 0.05:
            tag = "underconfident"
        else:
            tag = "well-calibrated"
        print(f"{labels[i]:<18}{cnt:>8}{acc:>13.1%}{tag:>18}")
        bin_stats.append((lo, min(hi, 1.0), labels[i], cnt, acc))

    print("-" * 66)

    # Interpretation note.
    over = [b for b in bin_stats if b[4] is not None
            and b[4] < ((b[0] + b[1]) / 2.0) - 0.05]
    if over:
        print("[interpretation] One or more buckets are OVERCONFIDENT: the model's")
        print("                 stated probability exceeds its real accuracy there.")
        print("                 This is a well-known classifier/LLM calibration")
        print("                 pitfall - we do NOT trust raw predict_proba at face")
        print("                 value; the threshold below is derived empirically.")
    else:
        print("[interpretation] Tier-1 confidence is reasonably calibrated across")
        print("                 populated buckets; higher confidence does track")
        print("                 higher actual accuracy.")

    # ---- Derive threshold ------------------------------------------------- #
    # Rule (stated): choose the LOWEST confidence value at/above which Tier-1's
    # actual accuracy stays >= TIER1_ACCEPT_ACCURACY_TARGET. This is now done by
    # the reusable derive_threshold_for_target() helper, called with the primary
    # 0.90 target so the printed output and behavior are UNCHANGED.
    derived, chosen_edge = derive_threshold_for_target(
        tier1_conf, correct, TIER1_ACCEPT_ACCURACY_TARGET
    )

    print("\n[threshold derivation]")
    print(f"  Rule: accept Tier-1 (skip escalation) only where its ACTUAL")
    print(f"        accuracy on accepted tickets stays >= "
          f"{TIER1_ACCEPT_ACCURACY_TARGET:.0%}.")
    if chosen_edge is not None:
        mask = tier1_conf >= derived
        cum_acc = float(correct[mask].mean()) if mask.sum() > 0 else 0.0
        share = float(mask.mean())
        print(f"  Lowest confidence edge holding that target: {derived:.2f}")
        print(f"  At conf >= {derived:.2f}: accept accuracy = {cum_acc:.1%}, "
              f"covers {share:.1%} of test tickets.")
    else:
        print("  No confidence band sustained the target accuracy on accepted")
        print(f"  tickets; escalating (almost) everything -> threshold={derived:.2f}.")
    print(f"  => CASCADE_CONFIDENCE_THRESHOLD = {min(derived, 1.0):.2f}")

    return float(min(derived, 1.0)) if derived <= 1.0 else float(derived)


def run_calibration_analysis_on_calibration_set(y_true, tier1_preds, tier1_conf):
    """Same calibration/derivation logic as run_calibration_analysis, but run on
    the SEPARATE paraphrased calibration set (loaded from
    data/calibration_tickets_paraphrased.json) instead of the in-distribution
    held-out split.

    Why a separate function/set: the held-out 800-row split is drawn from the
    same synthetic templates as training, so Tier-1 looks ~100% accurate in
    every bucket there and the derivation picks an unreliably-low threshold that
    fails on real out-of-distribution phrasing. The paraphrased calibration set
    is plain, non-template text, so its buckets reveal where Tier-1 actually
    becomes untrustworthy. The threshold derived HERE is the one applied to the
    cascade.

    Prints the SAME bucket table format (bucket | count | actual acc |
    over/under tag) and derives the threshold with the SAME rule (lowest
    confidence edge sustaining >= TIER1_ACCEPT_ACCURACY_TARGET cumulative
    accuracy). It also surfaces raw bucket counts prominently and prints a
    per-bucket caution when a populated bucket has fewer than 5 tickets.
    Returns the derived threshold (float).
    """
    y_true = np.asarray(y_true)
    tier1_preds = np.asarray(tier1_preds)
    tier1_conf = np.asarray(tier1_conf)
    correct = (tier1_preds == y_true).astype(int)

    edges = [0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0001]
    labels = ["<50%", "50-60%", "60-70%", "70-80%", "80-90%", "90-100%"]

    print("\n" + "=" * 66)
    print("TIER-1 CONFIDENCE CALIBRATION (separate paraphrased calibration set)")
    print("=" * 66)
    print(f"  Sample size: {len(tier1_conf)} paraphrased, non-template tickets "
          f"(full-data Tier-1 model).")
    print(f"  Out-of-distribution by design - this is what we DERIVE the applied")
    print(f"  cascade threshold from (NOT the in-distribution held-out split).")
    print("-" * 66)
    print(f"{'confidence bucket':<18}{'count':>8}{'actual acc':>14}"
          f"{'over/under?':>18}")
    print("-" * 66)

    small_buckets = []  # (label, count) for populated buckets with < 5 tickets
    bin_stats = []      # (lo, hi, label, count, acc)
    for i in range(len(labels)):
        lo, hi = edges[i], edges[i + 1]
        mask = (tier1_conf >= lo) & (tier1_conf < hi)
        cnt = int(mask.sum())
        if cnt == 0:
            print(f"{labels[i]:<18}{cnt:>8}{'-':>14}{'':>18}")
            bin_stats.append((lo, min(hi, 1.0), labels[i], 0, None))
            continue
        acc = float(correct[mask].mean())
        mid = (lo + min(hi, 1.0)) / 2.0
        if acc < mid - 0.05:
            tag = "OVERCONFIDENT"
        elif acc > mid + 0.05:
            tag = "underconfident"
        else:
            tag = "well-calibrated"
        print(f"{labels[i]:<18}{cnt:>8}{acc:>13.1%}{tag:>18}")
        bin_stats.append((lo, min(hi, 1.0), labels[i], cnt, acc))
        if cnt < 5:
            small_buckets.append((labels[i], cnt))

    print("-" * 66)

    # Prominent raw-count summary (small-sample transparency).
    print("[raw bucket counts] " + "  ".join(
        f"{lab}={b[3]}" for lab, b in zip(labels, bin_stats)
    ))
    print(f"[raw bucket counts] total populated tickets: {int((tier1_conf >= 0).sum())}")

    # Explicit small-sample cautions.
    if small_buckets:
        for lab, cnt in small_buckets:
            print(f"[caution] bucket {lab} has only {cnt} tickets - treat this "
                  f"accuracy estimate as noisy.")
    else:
        print("[note] All populated buckets have >= 5 tickets.")

    # Interpretation note.
    over = [b for b in bin_stats if b[4] is not None
            and b[4] < ((b[0] + b[1]) / 2.0) - 0.05]
    if over:
        print("[interpretation] One or more buckets are OVERCONFIDENT on this")
        print("                 out-of-distribution set: Tier-1's stated")
        print("                 probability exceeds its real accuracy there. This")
        print("                 is exactly the failure the held-out split hid, and")
        print("                 the reason we derive the applied threshold here.")
    else:
        print("[interpretation] Tier-1 confidence tracks actual accuracy")
        print("                 reasonably on this out-of-distribution set across")
        print("                 populated buckets.")

    # ---- Derive threshold (SAME rule as run_calibration_analysis) --------- #
    # Uses the reusable derive_threshold_for_target() helper with the primary
    # 0.90 target so this call site's printed output and behavior are UNCHANGED.
    derived, chosen_edge = derive_threshold_for_target(
        tier1_conf, correct, TIER1_ACCEPT_ACCURACY_TARGET
    )

    print("\n[threshold derivation - calibration set]")
    print(f"  Rule: accept Tier-1 (skip escalation) only where its ACTUAL")
    print(f"        accuracy on accepted tickets stays >= "
          f"{TIER1_ACCEPT_ACCURACY_TARGET:.0%}.")
    if chosen_edge is not None:
        mask = tier1_conf >= derived
        cum_acc = float(correct[mask].mean()) if mask.sum() > 0 else 0.0
        share = float(mask.mean())
        print(f"  Lowest confidence edge holding that target: {derived:.2f}")
        print(f"  At conf >= {derived:.2f}: accept accuracy = {cum_acc:.1%}, "
              f"covers {share:.1%} of calibration tickets.")
    else:
        print("  No confidence band sustained the target accuracy on accepted")
        print(f"  tickets; escalating (almost) everything -> threshold={derived:.2f}.")
    print(f"  => CASCADE_CONFIDENCE_THRESHOLD = {min(derived, 1.0):.2f}  (APPLIED)")

    return float(min(derived, 1.0)) if derived <= 1.0 else float(derived)


# --------------------------------------------------------------------------- #
# Confusion matrix printing (same style as train_embeddings.py)                #
# --------------------------------------------------------------------------- #
def print_labeled_confusion_matrix(y_true, y_pred, labels):
    """Print a labeled confusion matrix: rows=true, cols=predicted, names shown."""
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    # Short codes keep columns narrow but names are printed in a legend.
    codes = [f"C{i}" for i in range(len(labels))]
    colw = max(6, max(len(c) for c in codes) + 1)

    print("\nConfusion matrix (rows = TRUE, cols = PREDICTED):")
    print("Legend:")
    for c, name in zip(codes, labels):
        print(f"  {c} = {name}")

    header = " " * 14 + "".join(f"{c:>{colw}}" for c in codes)
    print(header)
    for i, name in enumerate(labels):
        row = f"{name[:13]:<14}" + "".join(f"{cm[i][j]:>{colw}}" for j in range(len(labels)))
        print(row)


# --------------------------------------------------------------------------- #
# Cascade execution                                                            #
# --------------------------------------------------------------------------- #
def run_cascade(texts, tier1_vec, tier1_clf, tier2_clf, embedder_or_emb,
                threshold, tier2_emb=None):
    """Run the cascade over `texts`.

    For each ticket: get Tier-1 prediction + confidence. If confidence >=
    threshold -> use Tier-1. Otherwise -> use Tier-2 (embeddings clf).

    `tier2_emb` may be supplied when embeddings for exactly these texts are
    already available (e.g. sliced from the cached full-dataset embeddings);
    otherwise pass an embedder model in `embedder_or_emb` to encode on demand.

    Returns dict with: preds (list), tiers (list of 1/2), tier1_conf (np array),
    n_tier1, n_tier2.
    """
    texts = list(texts)
    t1_preds, t1_conf = get_tier1_confidence(tier1_vec, tier1_clf, texts)

    escalate_idx = np.where(t1_conf < threshold)[0]

    final_preds = list(t1_preds)
    tiers = [1] * len(texts)

    if len(escalate_idx) > 0:
        if tier2_emb is not None:
            esc_emb = tier2_emb[escalate_idx]
        else:
            esc_texts = [texts[i] for i in escalate_idx]
            esc_emb = embedder_or_emb.encode(esc_texts, convert_to_numpy=True)
            esc_emb = np.asarray(esc_emb, dtype=np.float32)
        t2_preds = tier2_clf.predict(esc_emb)
        for k, idx in enumerate(escalate_idx):
            final_preds[idx] = t2_preds[k]
            tiers[idx] = 2

    n_tier2 = int(len(escalate_idx))
    n_tier1 = len(texts) - n_tier2
    return {
        "preds": final_preds,
        "tiers": tiers,
        "tier1_conf": t1_conf,
        "n_tier1": n_tier1,
        "n_tier2": n_tier2,
    }


def validate_novel_labels(training_categories):
    """Ensure every NOVEL_TICKETS expected label matches a real training class.

    Exits with a clear mismatch report if any expected label is unknown.
    """
    known = set(training_categories)
    mismatches = []
    for i, t in enumerate(NOVEL_TICKETS):
        if t["expected"] not in known:
            mismatches.append((i, t["expected"]))
    if mismatches:
        print("[ERROR] NOVEL_TICKETS contains expected labels that do NOT match "
              "any training category:")
        for i, lab in mismatches:
            print(f"        novel ticket #{i}: expected='{lab}' (not in training set)")
        print(f"        Known training categories: {sorted(known)}")
        sys.exit(1)
    print(f"[check] All {len(NOVEL_TICKETS)} novel-ticket labels match real "
          f"training categories.")


def validate_loaded_calibration_labels(calibration_tickets, training_categories):
    """Ensure every loaded calibration-set expected label matches a real training
    class. Mirrors validate_novel_labels.

    Exits with a clear mismatch report if any expected label is unknown - bad
    records are reported, not silently dropped.
    """
    known = set(training_categories)
    mismatches = []
    for i, t in enumerate(calibration_tickets):
        if t["expected"] not in known:
            mismatches.append((i, t["expected"]))
    if mismatches:
        print("[ERROR] The loaded calibration set contains expected labels that "
              "do NOT match any training category:")
        for i, lab in mismatches:
            print(f"        calibration ticket #{i}: expected='{lab}' "
                  f"(not in training set)")
        print(f"        Known training categories: {sorted(known)}")
        print("        Regenerate the calibration set with:")
        print("            python src/classification/generate_calibration_set.py")
        sys.exit(1)
    print(f"[check] All {len(calibration_tickets)} calibration-ticket labels "
          f"match real training categories.")


# --------------------------------------------------------------------------- #
# Accuracy / efficiency tradeoff analysis across target accuracy bars          #
# --------------------------------------------------------------------------- #
def run_tradeoff_analysis(calib_conf, calib_correct,
                          X_test_text, y_test, test_emb,
                          tier1_vec, tier1_clf, tier2_clf,
                          novel_texts, novel_expected, novel_emb,
                          tier1_vec_full, tier1_clf_full, tier2_clf_full):
    """Sweep several target accuracy bars and report the resulting tradeoff.

    For EACH target in ACCURACY_TARGETS_TO_TEST this:
      (a) derives a threshold with derive_threshold_for_target() against the
          SAME 175-ticket calibration set Tier-1 confidences/correctness that
          the main calibration table already computed (passed in as calib_conf /
          calib_correct - nothing is recomputed here);
      (b) runs the EXISTING run_cascade() once on the held-out split (reusing
          test_emb as tier2_emb) and once on the 14 novel tickets (reusing
          novel_emb as tier2_emb) - the same pattern used elsewhere in main();
      (c) computes % resolved at Tier-1 and cascade accuracy for BOTH sets;
      (d) stores a row dict for the comparison table.

    IMPORTANT: this function does NOT recompute embeddings, does NOT re-fit any
    model, and does NOT call Gemini. It only reuses objects already built in
    main(). The held-out split is evaluated with the SPLIT-trained tiers
    (tier1_vec/tier1_clf/tier2_clf) and the novel tickets with the FULL-data
    tiers (tier1_vec_full/tier1_clf_full/tier2_clf_full), exactly matching the
    single-threshold evaluation sections earlier in main().

    Returns the list of row dicts (also surfaced under main()'s results dict).
    """
    calib_conf = np.asarray(calib_conf)
    calib_correct = np.asarray(calib_correct)
    y_test = np.asarray(y_test)
    n_test = len(X_test_text)
    n_novel = len(novel_texts)
    novel_expected = list(novel_expected)

    rows = []
    for target in ACCURACY_TARGETS_TO_TEST:
        # (a) Derive threshold for THIS target from the calibration set data.
        derived, _chosen_edge = derive_threshold_for_target(
            calib_conf, calib_correct, target
        )
        # Applied threshold clamps to <= 1.0 exactly like the main call sites.
        applied_threshold = min(derived, 1.0) if derived <= 1.0 else derived

        # (b1) Cascade on the held-out split (split-trained tiers, test_emb).
        cas_test = run_cascade(
            X_test_text, tier1_vec, tier1_clf, tier2_clf,
            embedder_or_emb=None, threshold=applied_threshold,
            tier2_emb=test_emb,
        )
        held_tier1_pct = cas_test["n_tier1"] / n_test if n_test else 0.0
        held_acc = accuracy_score(y_test, cas_test["preds"])

        # (b2) Cascade on the 14 novel tickets (full-data tiers, novel_emb).
        cas_novel = run_cascade(
            novel_texts, tier1_vec_full, tier1_clf_full, tier2_clf_full,
            embedder_or_emb=None, threshold=applied_threshold,
            tier2_emb=novel_emb,
        )
        novel_tier1_pct = cas_novel["n_tier1"] / n_novel if n_novel else 0.0
        novel_correct = sum(
            1 for i in range(n_novel)
            if cas_novel["preds"][i] == novel_expected[i]
        )
        novel_acc = novel_correct / n_novel if n_novel else 0.0

        rows.append({
            "target_accuracy": float(target),
            "derived_threshold": float(applied_threshold),
            "held_out_tier1_pct": float(held_tier1_pct),
            "held_out_cascade_accuracy": float(held_acc),
            "novel_tier1_pct": float(novel_tier1_pct),
            "novel_cascade_accuracy": float(novel_acc),
        })

    # ---- Print the tradeoff table --------------------------------------- #
    print("\n" + "=" * 84)
    print("ACCURACY/EFFICIENCY TRADEOFF ACROSS TARGET BARS")
    print("=" * 84)
    print(f"{'Target Acc':<12}{'Threshold':<12}{'Held-out Tier1%':<18}"
          f"{'Held-out Acc':<15}{'Novel Tier1%':<15}{'Novel Acc':<12}")
    print("-" * 84)
    for r in rows:
        print(f"{r['target_accuracy']:<12.0%}"
              f"{r['derived_threshold']:<12.2f}"
              f"{r['held_out_tier1_pct']:<18.1%}"
              f"{r['held_out_cascade_accuracy']:<15.1%}"
              f"{r['novel_tier1_pct']:<15.1%}"
              f"{r['novel_cascade_accuracy']:<12.1%}")
    print("-" * 84)

    # ---- Plain-language interpretation ---------------------------------- #
    # Identify the 90%-target novel accuracy as the reference point (the primary
    # single-threshold result), plus any bar producing meaningful Tier-1 usage.
    ref_row = next((r for r in rows
                    if abs(r["target_accuracy"] - TIER1_ACCEPT_ACCURACY_TARGET) < 1e-9),
                   None)
    ref_novel_acc = ref_row["novel_cascade_accuracy"] if ref_row else None

    meaningful = [
        r for r in rows
        if r["held_out_tier1_pct"] > 0.0 or r["novel_tier1_pct"] > 0.0
    ]

    print("\n[tradeoff interpretation]")
    if not meaningful:
        # Genuine negative finding across ALL tested bars.
        print("  No target accuracy in ACCURACY_TARGETS_TO_TEST "
              f"({', '.join(f'{t:.0%}' for t in ACCURACY_TARGETS_TO_TEST)}) "
              "produced")
        print("  any Tier-1 usage on EITHER the held-out split or the novel")
        print("  tickets: every derived threshold routed 100% of tickets to")
        print("  Tier-2. This is a genuine negative finding - the calibration")
        print("  set's confidence distribution simply does not support cascading")
        print("  at any of these accuracy bars. In other words, TF-IDF Tier-1 is")
        print("  never trustworthy enough on out-of-distribution phrasing to skip")
        print("  the expensive tier while still holding even a 70% accept bar.")
        # NOTE: Even lower targets (e.g. 0.50) could be added to
        # ACCURACY_TARGETS_TO_TEST to force some Tier-1 usage, but they would
        # likely sacrifice unacceptable accuracy: TF-IDF's known standalone
        # novel-ticket accuracy in this project is only ~50% (BASELINE_TFIDF_NOVEL
        # = 7/14), so accepting Tier-1 at a 50% bar would drag cascade accuracy
        # toward that floor rather than preserving the MiniLM-level ~71.4%.
        print("  (A ~50% bar could be tested but would likely drag accuracy toward")
        print("  TF-IDF's ~50% standalone novel-ticket floor - not worth it.)")
    else:
        # At least one bar yields real cheap-tier usage - state the tradeoff.
        print("  The following target accuracy bar(s) produced non-zero Tier-1")
        print("  usage (i.e. real cheap-tier routing) on at least one set:")
        for r in meaningful:
            where = []
            if r["held_out_tier1_pct"] > 0.0:
                where.append(f"held-out {r['held_out_tier1_pct']:.1%}")
            if r["novel_tier1_pct"] > 0.0:
                where.append(f"novel {r['novel_tier1_pct']:.1%}")
            print(f"    - target {r['target_accuracy']:.0%}: "
                  f"threshold {r['derived_threshold']:.2f}, "
                  f"Tier-1 usage [{', '.join(where)}]")
        # Spell out the tradeoff for the LOWEST meaningful bar on the novel set.
        best = sorted(meaningful, key=lambda r: r["target_accuracy"])[0]
        if ref_novel_acc is not None:
            print()
            print(f"  Lowering the target to {best['target_accuracy']:.0%} derives a "
                  f"threshold of {best['derived_threshold']:.2f}, routing "
                  f"{best['novel_tier1_pct']:.1%} of novel")
            print(f"  tickets through the cheap tier, at a cost of "
                  f"{best['novel_cascade_accuracy']:.1%} novel accuracy vs "
                  f"{ref_novel_acc:.1%} at the")
            print(f"  {TIER1_ACCEPT_ACCURACY_TARGET:.0%} target on the novel benchmark.")

    return rows


# --------------------------------------------------------------------------- #
# Main pipeline                                                                #
# --------------------------------------------------------------------------- #
def main():
    print("=" * 66)
    print("CONFIDENCE-BASED CASCADE CLASSIFIER  (Tier1 TF-IDF -> Tier2 MiniLM)")
    print("=" * 66)
    print("Philosophy: same 'escalate when unsure' guard as the RAG layer's")
    print("SIMILARITY_THRESHOLD=0.35 - applied here at model-selection time.")

    # ---------------- Load + validate ------------------------------------- #
    df = load_and_validate_csv(CSV_PATH)
    df = df.reset_index(drop=True)
    text_all = build_text_series(df)
    y_all = df["category"].astype(str).to_numpy()
    training_categories = sorted(df["category"].unique())

    # Validate novel labels up front, before any prediction work.
    validate_novel_labels(training_categories)
    # Load + validate the paraphrased calibration set up front too (mirrors the
    # novel-label check). This fully replaces the old CALIBRATION_TICKETS list.
    calibration_tickets = load_calibration_set()
    validate_loaded_calibration_labels(calibration_tickets, training_categories)

    # ---------------- Standard split -------------------------------------- #
    # Split on the ROW INDEX so we can reuse the same 800 rows for both the
    # TF-IDF text path and the cached-embedding path (aligned indexing).
    idx_all = np.arange(len(df))
    idx_train, idx_test, y_train, y_test = standard_split(idx_all, y_all)
    print(f"\n[split] train={len(idx_train)} rows, test={len(idx_test)} rows "
          f"(test_size={TEST_SIZE}, random_state={RANDOM_STATE}, stratified). "
          f"Same 800-row held-out set as train_embeddings.py.")

    X_train_text = text_all.iloc[idx_train].tolist()
    X_test_text = text_all.iloc[idx_test].tolist()

    # ---------------- Full-dataset embeddings (cached) -------------------- #
    # Compute/reuse embeddings for the FULL dataset once; slice for train/test.
    full_emb = compute_or_load_embeddings(text_all.tolist(), expected_rows=len(df),
                                          use_cache=True)
    train_emb = full_emb[idx_train]
    test_emb = full_emb[idx_test]

    # ---------------- Train both tiers on the 80% split ------------------- #
    print("\n[train] Fitting Tier-1 (TF-IDF + LogReg) on the training split...")
    tier1_vec, tier1_clf = train_tier1(X_train_text, y_train)

    print("[train] Fitting Tier-2 (MiniLM emb + LogReg) on the training split...")
    tier2_clf = train_tier2_from_embeddings(train_emb, y_train)

    # Sanity: report standalone tier accuracies on the held-out split.
    t1_preds_test, t1_conf_test = get_tier1_confidence(tier1_vec, tier1_clf, X_test_text)
    t2_preds_test = tier2_clf.predict(test_emb)
    print(f"[baseline] Tier-1 alone test accuracy : "
          f"{accuracy_score(y_test, t1_preds_test):.4f}")
    print(f"[baseline] Tier-2 alone test accuracy : "
          f"{accuracy_score(y_test, t2_preds_test):.4f}")

    # ---------------- Retrain on FULL data for novel-ticket test ---------- #
    # The novel-ticket generalization test ALWAYS uses models trained on ALL
    # data (matching generalization_test_embeddings.py), not just the 80%.
    # We train the FULL-data models here (earlier than before) because the
    # calibration-set analysis also uses the full-data Tier-1 model, matching
    # the convention that novel-ticket-style evaluation uses the full-data model.
    print("\n" + "=" * 66)
    print("RETRAIN ON FULL 4000-ROW DATASET FOR NOVEL-TICKET GENERALIZATION")
    print("=" * 66)
    tier1_vec_full, tier1_clf_full = train_tier1(text_all.tolist(), y_all)
    tier2_clf_full = train_tier2_from_embeddings(full_emb, y_all)
    print("[train] Both tiers retrained on all 4000 rows.")

    # ---------------- Calibration + threshold derivation ------------------ #
    # We print TWO calibration analyses side by side for comparison:
    #   (1) the ORIGINAL held-out-split calibration (in-distribution),
    #   (2) the NEW separate paraphrased calibration-set calibration (OOD).
    # The threshold ACTUALLY APPLIED to the cascade is the one derived from (2),
    # because the in-distribution split hides Tier-1 overconfidence.
    global CASCADE_CONFIDENCE_THRESHOLD

    # (1) Original held-out-split calibration (kept, printed first).
    heldout_threshold = run_calibration_analysis(y_test, t1_preds_test, t1_conf_test)
    print(f"\n[threshold] Held-out-split-derived threshold (for reference only): "
          f"{heldout_threshold:.2f}")

    # (2) NEW calibration-set calibration, using the FULL-data Tier-1 model.
    calib_texts = [t["text"] for t in calibration_tickets]
    calib_expected = np.array([t["expected"] for t in calibration_tickets])
    calib_preds, calib_conf = get_tier1_confidence(
        tier1_vec_full, tier1_clf_full, calib_texts
    )
    calib_threshold = run_calibration_analysis_on_calibration_set(
        calib_expected, calib_preds, calib_conf
    )

    # Precompute per-ticket correctness for the calibration set once, so the
    # tradeoff analysis can reuse EXACTLY this data (no recompute).
    calib_correct = (np.asarray(calib_preds) == calib_expected).astype(int)

    # APPLY the calibration-set-derived threshold to the cascade.
    CASCADE_CONFIDENCE_THRESHOLD = calib_threshold
    print(f"\n[threshold] Using CASCADE_CONFIDENCE_THRESHOLD = "
          f"{CASCADE_CONFIDENCE_THRESHOLD:.2f}  (derived from the separate "
          f"calibration set, not the held-out split).")

    # ---------------- Run cascade on held-out 800-row test ---------------- #
    print("\n" + "=" * 66)
    print("CASCADE ON HELD-OUT TEST SPLIT")
    print("=" * 66)
    cas = run_cascade(
        X_test_text, tier1_vec, tier1_clf, tier2_clf,
        embedder_or_emb=None, threshold=CASCADE_CONFIDENCE_THRESHOLD,
        tier2_emb=test_emb,
    )
    cas_preds = cas["preds"]
    n = len(X_test_text)
    print(f"Resolved at Tier-1 : {cas['n_tier1']:>4} / {n}  "
          f"({cas['n_tier1'] / n:.1%})")
    print(f"Escalated to Tier-2: {cas['n_tier2']:>4} / {n}  "
          f"({cas['n_tier2'] / n:.1%})")

    cas_acc = accuracy_score(y_test, cas_preds)
    cas_macro_f1 = f1_score(y_test, cas_preds, average="macro")
    cas_weighted_f1 = f1_score(y_test, cas_preds, average="weighted")
    print(f"\nCascade accuracy    : {cas_acc:.4f}")
    print(f"Cascade macro F1    : {cas_macro_f1:.4f}")
    print(f"Cascade weighted F1 : {cas_weighted_f1:.4f}")

    print("\nClassification report (cascade, held-out test split):")
    print(classification_report(y_test, cas_preds,
                                labels=training_categories, zero_division=0))
    print_labeled_confusion_matrix(y_test, cas_preds, training_categories)

    test_tier1_pct = cas["n_tier1"] / n
    test_tier2_pct = cas["n_tier2"] / n

    # ---------------- Novel-ticket generalization ------------------------- #
    # Embed the 14 novel tickets on the fly (not part of the cache).
    novel_texts = [t["text"] for t in NOVEL_TICKETS]
    novel_expected = [t["expected"] for t in NOVEL_TICKETS]
    embedder = _load_embedder()
    novel_emb = np.asarray(
        embedder.encode(novel_texts, convert_to_numpy=True), dtype=np.float32
    )

    cas_novel = run_cascade(
        novel_texts, tier1_vec_full, tier1_clf_full, tier2_clf_full,
        embedder_or_emb=embedder, threshold=CASCADE_CONFIDENCE_THRESHOLD,
        tier2_emb=novel_emb,
    )
    novel_preds = cas_novel["preds"]
    novel_tiers = cas_novel["tiers"]
    novel_conf = cas_novel["tier1_conf"]

    print("\n" + "=" * 66)
    print("CASCADE ON 14 NOVEL TICKETS (models trained on FULL dataset)")
    print("=" * 66)
    correct_count = 0
    for i in range(len(NOVEL_TICKETS)):
        exp = novel_expected[i]
        pred = novel_preds[i]
        ok = (pred == exp)
        correct_count += int(ok)
        tag = "CORRECT" if ok else "WRONG"
        if novel_tiers[i] == 1:
            resolver = f"resolved by: Tier 1, confidence={novel_conf[i]:.2f}"
        else:
            resolver = f"resolved by: Tier 2, Tier 1 confidence was {novel_conf[i]:.2f}"
        print(f"[{tag}] expected={exp} predicted={pred} ({resolver})")

    novel_acc = correct_count / len(NOVEL_TICKETS)
    novel_tier1 = novel_tiers.count(1)
    novel_tier2 = novel_tiers.count(2)
    print(f"\nNovel-ticket cascade score: {correct_count}/{len(NOVEL_TICKETS)} "
          f"({novel_acc:.1%})")
    print(f"Resolved at Tier-1 : {novel_tier1}/{len(NOVEL_TICKETS)} "
          f"({novel_tier1 / len(NOVEL_TICKETS):.1%})")
    print(f"Escalated to Tier-2: {novel_tier2}/{len(NOVEL_TICKETS)} "
          f"({novel_tier2 / len(NOVEL_TICKETS):.1%})")

    # ---------------- Final comparison table ------------------------------ #
    tfidf_c, tfidf_n = BASELINE_TFIDF_NOVEL
    minilm_c, minilm_n = BASELINE_MINILM_NOVEL
    print("\n" + "-" * 66)
    print("EFFICIENCY STORY (FrugalGPT-style contribution)")
    print("-" * 66)
    novel_tier1_pct = novel_tier1 / len(NOVEL_TICKETS)
    print(f"  Novel tickets    : {novel_tier1_pct:.1%} resolved by "
          f"cheap Tier-1 alone; {novel_tier2 / len(NOVEL_TICKETS):.1%} escalated to Tier-2.")
    print(f"  Held-out test set: {test_tier1_pct:.1%} resolved by cheap Tier-1 "
          f"alone; {test_tier2_pct:.1%} escalated to Tier-2.")
    print()
    if novel_tier1_pct == 0.0 and test_tier1_pct == 0.0:
        print("  Interpretation: at the current CASCADE_CONFIDENCE_THRESHOLD, the")
        print("  cascade escalated 100% of tickets to Tier-2 on both evaluation")
        print("  sets - it collapsed to functionally identical behavior as running")
        print("  MiniLM alone. This is an honest negative efficiency result: at the")
        print(f"  {TIER1_ACCEPT_ACCURACY_TARGET:.0%} accuracy bar used to derive this")
        print("  threshold, no confidence level of Tier-1 (TF-IDF) was trustworthy")
        print("  enough on out-of-distribution phrasing to justify skipping Tier-2.")
        print("  No cost savings were realized under this target accuracy setting.")
    elif novel_tier1_pct == 0.0 or test_tier1_pct == 0.0:
        print("  Interpretation: Tier-1 resolved some tickets on one evaluation set")
        print("  but none on the other at this threshold - efficiency gains are")
        print("  inconsistent across distributions and should not be generalized")
        print("  from a single set. Report both numbers separately, not combined.")
    else:
        print("  Interpretation: every Tier-1-resolved ticket AVOIDS the ~100s-scale")
        print("  embedding path, so this efficiency figure is a real cost win even")
        print("  when end accuracy is only comparable to MiniLM-alone. Reported")
        print("  honestly either way - accuracy AND cost both matter.")

    # ---------------- Accuracy/efficiency tradeoff sweep ------------------ #
    # ADDITIONAL section: reuse everything already built above (no recompute of
    # embeddings, no re-fit, no Gemini call) to sweep multiple target accuracy
    # bars and report the tradeoff table. The single-threshold output above is
    # fully preserved and unchanged; this appears after it as a new section.
    tradeoff_rows = run_tradeoff_analysis(
        calib_conf=calib_conf,
        calib_correct=calib_correct,
        X_test_text=X_test_text,
        y_test=y_test,
        test_emb=test_emb,
        tier1_vec=tier1_vec,
        tier1_clf=tier1_clf,
        tier2_clf=tier2_clf,
        novel_texts=novel_texts,
        novel_expected=novel_expected,
        novel_emb=novel_emb,
        tier1_vec_full=tier1_vec_full,
        tier1_clf_full=tier1_clf_full,
        tier2_clf_full=tier2_clf_full,
    )

    print("\n[done] Cascade pipeline complete.")

    # Return a results dict so this can be imported by a future evaluation
    # script (e.g. the class-imbalance experiment) rather than only run stand-alone.
    return {
        "threshold": CASCADE_CONFIDENCE_THRESHOLD,
        "heldout_threshold": heldout_threshold,
        "calibration_threshold": calib_threshold,
        "test_accuracy": cas_acc,
        "test_macro_f1": cas_macro_f1,
        "test_weighted_f1": cas_weighted_f1,
        "test_tier1_pct": test_tier1_pct,
        "test_tier2_pct": test_tier2_pct,
        "novel_correct": correct_count,
        "novel_total": len(NOVEL_TICKETS),
        "novel_tier1": novel_tier1,
        "novel_tier2": novel_tier2,
        "tradeoff_analysis": tradeoff_rows,
    }


if __name__ == "__main__":
    main()
